Exception thrown in <main>(excp_trace_suc.moto:34)
Exception thrown in tharSheBlows(excp_trace_suc.moto:5)
   called from function <main>(excp_trace_suc.moto:53)
Exception thrown in tharSheBlows(excp_trace_suc.moto:5)
   called from function tharSheBlows(excp_trace_suc.moto:4)
   called from function <main>(excp_trace_suc.moto:59)
Exception thrown in tharSheBlows(excp_trace_suc.moto:5)
   called from function tharSheBlows(excp_trace_suc.moto:4)
   called from function tharSheBlows(excp_trace_suc.moto:4)
   called from function <main>(excp_trace_suc.moto:65)
Exception thrown in tharSheBlows(excp_trace_suc.moto:5)
   called from function tharSheBlows(excp_trace_suc.moto:4)
   called from function tharSheBlows(excp_trace_suc.moto:4)
   called from function <main>(excp_trace_suc.moto:65)
Exception thrown in tharSheBlows(excp_trace_suc.moto:5)
   called from function tharSheBlows(excp_trace_suc.moto:4)
   called from function tharSheBlows(excp_trace_suc.moto:4)
   called from function tharSheBlows(excp_trace_suc.moto:4)
   called from function catchHerTwiceWhenSheBlows(excp_trace_suc.moto:10)
   called from function <main>(excp_trace_suc.moto:71)
Exception thrown in tharSheBlows(excp_trace_suc.moto:5)
   called from function tharSheBlows(excp_trace_suc.moto:4)
   called from function tharSheBlows(excp_trace_suc.moto:4)
   called from function tharSheBlows(excp_trace_suc.moto:4)
   called from function catchHerTwiceWhenSheBlows(excp_trace_suc.moto:15)
   called from function <main>(excp_trace_suc.moto:71)
ArrayBoundsException thrown in explodeWithArrayBoundsException(excp_trace_suc.moto:22)
   called from function <main>(excp_trace_suc.moto:72)
ArrayBoundsException thrown in String::substring(mxstring.c:311)
   called from function explodeWithNativeMethodCall(excp_trace_suc.moto:30)
   called from function <main>(excp_trace_suc.moto:74)
ArrayBoundsException thrown in String::substring(mxstring.c:311)
   called from function explodeWithNativeMethodCall(excp_trace_suc.moto:30)
   called from method Exploder::Exploder(excp_trace_suc.moto:45)
   called from function <main>(excp_trace_suc.moto:76)
ArrayBoundsException thrown in explodeWithArrayBoundsException(excp_trace_suc.moto:22)
   called from method Exploder::explode(excp_trace_suc.moto:46)
   called from function <main>(excp_trace_suc.moto:77)
Exception thrown in explodeWithExploder(excp_trace_suc.moto:41)
   called from method Exploder::explode(excp_trace_suc.moto:48)
   called from function explodeWithExploder(excp_trace_suc.moto:40)
   called from method Exploder::explode(excp_trace_suc.moto:48)
   called from function explodeWithExploder(excp_trace_suc.moto:40)
   called from method Exploder::explode(excp_trace_suc.moto:48)
   called from function <main>(excp_trace_suc.moto:80)

